apiVersion: v2
name: akto-mini-runtime-versioned
description: Helm chart for installing Akto hybrid runtime with all versioned image tags
type: application
version: 0.5.9
appVersion: "0.5.9"
home: https://www.akto.io
icon: https://akto-setup.s3.amazonaws.com/templates/128x128.png
sources:
  - https://github.com/akto-api-security/helm-charts/tree/master/charts/mini-runtime-versioned
keywords:
  - akto
  - api
  - api security
  - dast
maintainers:
  - name: Ankush Jain
    email: ankush@akto.io
dependencies:
  - name: akto-mini-runtime
    version: 0.5.9
    repository: file://../mini-runtime
