# This chart uses the mini-runtime chart with all versioned image tags
# Only overrides the runtime and threat-client images (which are "latest" in base chart)

akto-mini-runtime:
  mini_runtime:
    aktoApiSecurityRuntime:
      image:
        tag: 1.57.6_local

  threat_client:
    aktoApiSecurityThreatClient:
      image:
        tag: "1.6.7"
